name: Python CI

on: [push]

permissions:
  contents: read
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8

      # 4. Run unittests with coverage
      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover
          coverage report -m
          coverage xml

      # 5. Fail if coverage is below threshold (example: 80%)
      - name: Check coverage threshold
        run: coverage report --fail-under=80

      # 6. Run flake8 (syntax / style check)
      - name: Run flake8
        run: flake8 . --max-line-length=120 --exclude=*.pyc,.venv
